# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sx < Formula
  desc "Your team's private npm for AI assets - skills, MCP configs, commands, and more"
  homepage "https://github.com/sleuth-io/sx"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sleuth-io/sx/releases/download/v2.0.1/sx_Darwin_x86_64.tar.gz"
      sha256 "0472cd380e8329b412fa641a629f68e3e041d8c1dd2464735f97d90374cdd1de"

      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sleuth-io/sx/releases/download/v2.0.1/sx_Darwin_arm64.tar.gz"
      sha256 "a53e6ae47f94e25a2466188d63889d31fc744a0e6b14914bf18699c1f42db90e"

      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleuth-io/sx/releases/download/v2.0.1/sx_Linux_x86_64.tar.gz"
      sha256 "58f991d7d2fe09f9678914cee98defb4815d6e23a21e390c8ec90da2c3883c19"
      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleuth-io/sx/releases/download/v2.0.1/sx_Linux_arm64.tar.gz"
      sha256 "5169bd5d15df6d7f7e8fac5498ef0bca4135c591f56f0cbdbe97cbf5bb28341d"
      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  def caveats
    <<~EOS
      To let Homebrew manage updates, disable sx's auto-updater by adding
      to your shell profile:

        export DISABLE_AUTOUPDATER=1

      Then use `brew upgrade sx` to update.
    EOS
  end
end
