# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sx < Formula
  desc "Your team's private npm for AI assets - skills, MCP configs, commands, and more"
  homepage "https://github.com/sleuth-io/sx"
  version "0.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sleuth-io/sx/releases/download/v0.12.3/sx_Darwin_x86_64.tar.gz"
      sha256 "1f94dd330cb399b66cd1cc3e8c6d735f7aa1ea63d468c8f1c4e95eab1d67e51c"

      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sleuth-io/sx/releases/download/v0.12.3/sx_Darwin_arm64.tar.gz"
      sha256 "408df2b8a5788ba2a4be4e61d2c6e363063a227a65ca982e94536a5e86c29ada"

      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleuth-io/sx/releases/download/v0.12.3/sx_Linux_x86_64.tar.gz"
      sha256 "90c44d1070bb1cf76056f804d7994f993c592fc87a59dde25dc6892903c9b642"
      define_method(:install) do
        bin.install "sx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sleuth-io/sx/releases/download/v0.12.3/sx_Linux_arm64.tar.gz"
      sha256 "6f88024b982aaf37a6374578f38fdbf3f005f135429a4b08fa3d7849ea808856"
      define_method(:install) do
        bin.install "sx"
      end
    end
  end

  def caveats
    <<~EOS
      To let Homebrew manage updates, disable sx's auto-updater by adding
      to your shell profile:

        export DISABLE_AUTOUPDATER=1

      Then use `brew upgrade sx` to update.
    EOS
  end
end
